live_config_reload = true

[font]
size = 15.0

[font.normal]
family = "0xProto Nerd Font"

[font.offset]
y = 1

[scrolling]
history = 10000

[shell]
args = ["-c", "/opt/homebrew/bin/tmux a -t default || /opt/homebrew/bin/tmux new -s default"]
program = "/opt/homebrew/bin/tmux"

[window]
opacity = 0.9

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 8
y = 4

[window.position]
x = 0
y = 0
